// One-shot asset importer (corrections7).
//
// Next.js cannot read absolute Windows paths from the user's Desktop at
// runtime, so this script bundles those local assets into the project:
//
//   1. Reviews   — ../reviews/<folder>/New Text Document.txt (+ avatar image)
//                  → public/images/reviews/* and src/data/reviews.ts
//   2. Galleries — ../Location 1 - Кършияка/*, ../Location 2 - Сточна гара/*
//                  → public/images/locations/<key>/* and src/data/galleries.ts
//
// Run from the Site/ directory with:  node scripts/import-assets.mjs
// It is idempotent: the public folders are wiped and rebuilt on every run, and
// the generated data files are overwritten, so re-running picks up any changes
// to the source folders. The generated files are committed to the repo so the
// build never depends on the user's Desktop being present.

import { promises as fs } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const SITE_ROOT = path.resolve(__dirname, "..");
const PROJECT_ROOT = path.resolve(SITE_ROOT, ".."); // c:\Users\Rosen\Desktop\mygym
const PUBLIC_DIR = path.join(SITE_ROOT, "public");
const DATA_DIR = path.join(SITE_ROOT, "src", "data");

const IMAGE_EXT = new Set([".jpg", ".jpeg", ".png", ".webp"]);
// Authors pinned to the front of the list, in this order (corrections8).
const PINNED_AUTHORS = ["Nikolay Atanasov"];
// Extra review folders that sit in the project root (not under reviews/).
const EXTRA_REVIEW_DIRS = ["additonal review", "additonal review - Copy"];
const GENERATED_BANNER =
  "// AUTO-GENERATED by scripts/import-assets.mjs — do not edit by hand.\n" +
  "// Re-run `node scripts/import-assets.mjs` to regenerate from the source folders.\n\n";

/** Natural sort so "2.jpg" < "10.jpg" and "7 (1).jpg" sits sensibly. */
function naturalCompare(a, b) {
  return a.localeCompare(b, undefined, { numeric: true, sensitivity: "base" });
}

async function listImages(dir) {
  const entries = await fs.readdir(dir, { withFileTypes: true });
  return entries
    .filter((e) => e.isFile() && IMAGE_EXT.has(path.extname(e.name).toLowerCase()))
    .map((e) => e.name)
    .sort(naturalCompare);
}

async function resetDir(dir) {
  await fs.rm(dir, { recursive: true, force: true });
  await fs.mkdir(dir, { recursive: true });
}

// ---------------------------------------------------------------------------
// 1. Reviews
// ---------------------------------------------------------------------------

/**
 * Parse one "New Text Document.txt". Shape copied from Google Reviews:
 *   <author name>
 *   <blank lines where the star row + date sat>
 *   преди N <месеца|седмици|месец>      ← "N <time> ago"
 *   <review body, one or more lines>
 */
function parseReviewText(raw) {
  const lines = raw
    .replace(/\r\n/g, "\n")
    .split("\n")
    .map((l) => l.trim());
  const nonEmpty = lines.filter(Boolean);
  if (nonEmpty.length === 0) return null;

  const author = nonEmpty[0];

  // Star rating: the source copies carry no ★ glyphs, but support them in case
  // future exports do. These are all 5-star Google reviews otherwise.
  const stars = (raw.match(/[★⭐]/gu) || []).length;
  const rating = stars >= 1 && stars <= 5 ? stars : 5;

  // Body = everything after the time-ago marker line, in either the Bulgarian
  // ("преди N месеца") or English ("N days ago") Google Reviews format.
  const markerIdx = lines.findIndex(
    (l) => /^преди\s/i.test(l) || /\bago\b/i.test(l)
  );
  const bodyLines =
    markerIdx >= 0 ? lines.slice(markerIdx + 1) : nonEmpty.slice(1);
  const text = bodyLines.filter(Boolean).join(" ").trim();

  return { author, rating, text };
}

async function importReviews() {
  const srcRoot = path.join(PROJECT_ROOT, "reviews");
  const outImgDir = path.join(PUBLIC_DIR, "images", "reviews");
  await resetDir(outImgDir);

  const folderPaths = (await fs.readdir(srcRoot, { withFileTypes: true }))
    .filter((e) => e.isDirectory())
    .map((e) => e.name)
    .sort(naturalCompare)
    .map((name) => path.join(srcRoot, name));

  // Extra standalone review folders that live in the project root rather than
  // under reviews/ (corrections8). Appended after the main set.
  for (const dir of EXTRA_REVIEW_DIRS) {
    folderPaths.push(path.join(PROJECT_ROOT, dir));
  }

  // First pass: parse every review (and note its avatar source) without
  // assigning ids yet, so we can order them before numbering.
  const parsedReviews = [];
  for (const folderPath of folderPaths) {
    const files = await fs.readdir(folderPath);
    const txt = files.find((f) => f.toLowerCase().endsWith(".txt"));
    if (!txt) continue;

    const raw = await fs.readFile(path.join(folderPath, txt), "utf8");
    const parsed = parseReviewText(raw);
    if (!parsed || !parsed.text) continue;

    const imgFile = files.find((f) =>
      IMAGE_EXT.has(path.extname(f).toLowerCase())
    );
    parsedReviews.push({ ...parsed, folderPath, imgFile });
  }

  // Pinned authors come first (in PINNED_AUTHORS order); the rest keep their
  // natural folder order.
  parsedReviews.sort((a, b) => {
    const pa = PINNED_AUTHORS.indexOf(a.author);
    const pb = PINNED_AUTHORS.indexOf(b.author);
    if (pa !== -1 || pb !== -1)
      return (pa === -1 ? Infinity : pa) - (pb === -1 ? Infinity : pb);
    return 0;
  });

  // Second pass: assign sequential ids and copy avatars in final order.
  const reviews = [];
  let idx = 0;
  for (const { author, rating, text, folderPath, imgFile } of parsedReviews) {
    idx += 1;
    const id = `r${idx}`;

    // Copy the avatar image if the folder has one; otherwise leave null so the
    // UI falls back to the default placeholder avatar.
    let avatar = null;
    if (imgFile) {
      const ext = path.extname(imgFile).toLowerCase();
      const fileName = `${id}${ext}`;
      await fs.copyFile(
        path.join(folderPath, imgFile),
        path.join(outImgDir, fileName)
      );
      avatar = `/images/reviews/${fileName}`;
    }

    reviews.push({ id, author, rating, text, avatar });
  }

  const body =
    GENERATED_BANNER +
    "export interface Review {\n" +
    "  id: string;\n" +
    "  author: string;\n" +
    "  rating: number;\n" +
    "  text: string;\n" +
    "  /** Public path to the reviewer photo, or null to use the default avatar. */\n" +
    "  avatar: string | null;\n" +
    "}\n\n" +
    `export const REVIEWS: readonly Review[] = ${JSON.stringify(reviews, null, 2)} as const;\n`;

  await fs.writeFile(path.join(DATA_DIR, "reviews.ts"), body, "utf8");
  console.log(
    `reviews: ${reviews.length} parsed, ${reviews.filter((r) => r.avatar).length} with photos`
  );
}

// ---------------------------------------------------------------------------
// 2. Location galleries
// ---------------------------------------------------------------------------

const GALLERY_SOURCES = [
  { key: "karshiyaka", dir: "Location 1 - Кършияка" },
  { key: "stochna", dir: "Location 2 - Сточна гара" },
];

async function importGalleries() {
  const galleries = {};
  for (const { key, dir } of GALLERY_SOURCES) {
    const srcDir = path.join(PROJECT_ROOT, dir);
    const outDir = path.join(PUBLIC_DIR, "images", "locations", key);
    await resetDir(outDir);

    const images = await listImages(srcDir);
    const paths = [];
    let i = 0;
    for (const name of images) {
      i += 1;
      const ext = path.extname(name).toLowerCase();
      const fileName = `${String(i).padStart(2, "0")}${ext}`;
      await fs.copyFile(path.join(srcDir, name), path.join(outDir, fileName));
      paths.push(`/images/locations/${key}/${fileName}`);
    }
    galleries[key] = paths;
    console.log(`gallery ${key}: ${paths.length} images`);
  }

  const body =
    GENERATED_BANNER +
    'import type { LocationId } from "@/data/locations";\n\n' +
    "/** Public image paths for each location's lightbox gallery. */\n" +
    `export const GALLERIES: Record<LocationId, readonly string[]> = ${JSON.stringify(galleries, null, 2)} as const;\n`;

  await fs.writeFile(path.join(DATA_DIR, "galleries.ts"), body, "utf8");
}

await importReviews();
await importGalleries();
console.log("Done. Generated src/data/reviews.ts and src/data/galleries.ts.");
