// AUTO-GENERATED by scripts/import-assets.mjs — do not edit by hand.
// Re-run `node scripts/import-assets.mjs` to regenerate from the source folders.

import type { LocationId } from "@/data/locations";

/** Public image paths for each location's lightbox gallery. */
export const GALLERIES: Record<LocationId, readonly string[]> = {
  "karshiyaka": [
    "/images/locations/karshiyaka/01.jpg",
    "/images/locations/karshiyaka/02.jpg",
    "/images/locations/karshiyaka/03.jpg",
    "/images/locations/karshiyaka/04.jpg",
    "/images/locations/karshiyaka/05.jpg",
    "/images/locations/karshiyaka/06.jpg",
    "/images/locations/karshiyaka/07.jpg",
    "/images/locations/karshiyaka/08.jpg",
    "/images/locations/karshiyaka/09.jpg",
    "/images/locations/karshiyaka/10.jpg"
  ],
  "stochna": [
    "/images/locations/stochna/01.jpg",
    "/images/locations/stochna/02.jpg",
    "/images/locations/stochna/03.jpg",
    "/images/locations/stochna/04.jpg",
    "/images/locations/stochna/05.jpg",
    "/images/locations/stochna/06.jpg",
    "/images/locations/stochna/07.jpg",
    "/images/locations/stochna/08.jpg",
    "/images/locations/stochna/09.jpg",
    "/images/locations/stochna/10.jpg"
  ]
} as const;
